name: booking_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
 # Bloc for state management
  flutter_bloc: ^8.0.1
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # Service locator
  get_it: ^7.2.0
  # Remote API
  internet_connection_checker: ^0.0.1+3
  dio: ^4.0.6
  # Local cache
  shared_preferences: ^2.0.13
  # Toast
  fluttertoast: ^8.0.9
  # Conditions
  conditional_builder_null_safety: ^0.0.6
  # Image Cache
  cached_network_image: ^3.2.2
  image_picker: ^0.8.5+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/google.jpg
